services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      target: deps
    command: npm run dev
    environment:
      - BACKEND_URL=http://backend:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
